import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LowerFooter from "@/components/LowerFooter";

export const metadata: Metadata = {
  title: "Digital Real Estate Exchange | Grade-A Assets | Alt DRX",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        <LowerFooter />
      </body>
    </html>
  );
}
